<a href="https://colab.research.google.com/github/prasiddhiacharya/Ml-from-scratch/blob/main/01%20Introduction_to_Ml/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to NumPy

What will we cover?
- Creating arrays
- Multi dimensional array
- Randomly generated arrays
- Element wise Operations
   - Comparision operations
   - logical operations
-Summarizing opeartions


### Single Dimensional arrays


In [ ]:
import numpy as np

creating arrays

In [ ]:
 var = np.zeros(5)
 print(type(var))

<class 'numpy.ndarray'>


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
my_arr = np.array([1, 2, 3, 4])
my_arr[2]= 5
print(my_arr)

[1 2 5 4]


In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Multidimensional Arrays


In [ ]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# create an MD unit array of size (5,2)
# generate a random array of size (3,5) with elements of your choice
# update the element of an array with index


In [ ]:
n= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:
n[2,1]= 31
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 31,  9]])

In [ ]:
n[2]= [1, 1, 1]
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [ ]:
n[: , 2]= [2, 2, 2]
n



array([[1, 2, 2],
       [4, 5, 2],
       [1, 1, 2]])

### Randomly generated arrays

- NumPy can create arrays filled with random numbers.
- To ensure the repoducibility, you can set a seed using np.random.seed()
- Everytime you run a code with np.random.seed(2), it will generate the exact same random numbers. if you remove or change the seed values, the sequence of random numbers will be changed

In [ ]:
np.random.rand(3)

array([0.40957915, 0.58929883, 0.01512409, 0.0191069 , 0.95704376])